[package]
edition = "2024"
name = "cstree2d"
version = "0.1.0"

[dependencies]
cstree = {workspace = true}
indoc = {workspace = true}

[dev-dependencies]
cstree = {workspace = true, features = ["derive"]}

[lints]
workspace = true

[[example]]
name = "example"
path = "examples/example.rs"
